Repository abduljalilpalala/ps-slackana, pull requests merged in 2022-09, with the labels that each got.

#2 [slackana-01] - [Markup] User Sign Up Page
  client/.babelrc
  client/.eslintrc.json
  client/.prettierrc
  client/next.config.js
  client/package.json
  client/pages/_app.tsx
  client/pages/index.tsx
  client/postcss.config.js
  client/public/images/404.png
  client/public/images/under-construction.png
  client/src/helpers/classNames.ts
  client/src/pages/404.tsx
  client/src/pages/_app.tsx
  client/src/pages/_document.tsx
  client/src/pages/api/hello.ts
  client/src/pages/index.tsx
  client/src/pages/sign-in.tsx
  client/src/pages/sign-up.tsx
  client/src/shared/css/globals.css
  client/src/shared/css/tailwind.css
  client/src/shared/icons/GoogleIcon.tsx
  client/src/shared/icons/Logo2Icon.tsx
  client/src/shared/icons/LogoIcon.tsx
  client/src/shared/icons/SpinnerIcon.tsx
  client/src/shared/twin/404.styles.ts
  client/src/shared/twin/auth.styles.ts
  client/src/shared/twin/globals.styles.ts
  client/src/shared/twin/under-construction.styles.ts
  client/src/shared/types/index.ts
  client/src/shared/validation/index.ts
  client/src/utils/UnderContruction.tsx
  client/styledComponentsOverride.d.ts
  client/styles/Home.module.css
  client/styles/globals.css
  client/tailwind.config.js
  client/tsconfig.json
  client/yarn.lock
Labels: for-review, Approved by John ✅, Approved by AJ ✅

#3 [slackana-05] - [Markup] User Sign In Page
  client/src/components/AuthForm.tsx
  client/src/layouts/AuthLayout.tsx
  client/src/pages/sign-in.tsx
  client/src/pages/sign-up.tsx
  client/src/shared/twin/globals.styles.ts
  client/src/shared/validation/index.ts
Labels: for-review, Approved by John ✅, Approved by AJ ✅

#4 [slackana-08] - [Markup] User Layout
  client/next.config.js
  client/package.json
  client/public/images/animated-avatar.jpg
  client/public/images/default-avatar.png
  client/src/components/molecules/AuthForm/index.tsx
  client/src/components/molecules/NotificationPopover/index.tsx
  client/src/components/molecules/UserMenuDropdown/index.tsx
  client/src/components/molecules/UserMenuPopover/index.tsx
  client/src/components/organisms/Drawer/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/Sidebar/index.tsx
  client/src/components/templates/AuthLayout/index.tsx
  client/src/components/templates/HomeLayout/index.tsx
  client/src/components/templates/MenuTransition/index.tsx
  client/src/components/templates/PopoverTransition/index.tsx
  client/src/pages/index.tsx
  client/src/pages/sign-in.tsx
  client/src/pages/sign-up.tsx
  client/src/shared/css/tailwind.css
  client/src/shared/interfaces/index.ts
  client/src/shared/jsons/sidebarLinks.ts
  client/src/shared/jsons/teams.ts
  client/src/shared/twin/auth.styles.ts
  client/src/shared/twin/drawer.styles.ts
  client/src/shared/twin/globals.styles.ts
  client/src/shared/twin/header.styles.ts
  client/src/shared/twin/home-layout.styles.ts
  client/src/shared/twin/notification-popover.styles.ts
  client/src/shared/twin/sidebar.styles.ts
  client/src/shared/twin/user-menu-dropdown.styles.ts
  client/src/shared/twin/user-menu-popover.styles.ts
  client/tailwind.config.js
  client/yarn.lock
Labels: for-review, Approved by John ✅, Approved by AJ ✅, Approved by Kent ✅

#9 [slackana-18] - [Markup] Create Project Modal
  client/src/components/molecules/InputTags/index.tsx
  client/src/components/templates/DialogBox/index.tsx
  client/src/components/templates/DropDown/index.tsx
  client/src/components/templates/HomeLayout/index.tsx
  client/src/components/templates/ProjectListTemplate/index.tsx
  client/src/pages/index.tsx
  client/src/shared/icons/CloseIcon.tsx
  client/src/shared/jsons/projectStatusData.ts
  client/src/shared/twin/globals.styles.ts
  client/src/shared/twin/home-content.style.ts
  client/src/shared/twin/sidebar.styles.ts
Labels: dependent, For Code Review 💻, Approved by Joshua ✅

#12 [slackana-11] - [Markup] Create Settings Modal in Profile Avatar Dropdown
  client/src/components/atoms/SubmitButton/index.tsx
  client/src/components/atoms/SwitchToggle/index.tsx
  client/src/components/molecules/UserMenuPopover/index.tsx
  client/src/components/organisms/SettingsModal/index.tsx
  client/src/components/templates/DialogBox/index.tsx
  client/src/pages/index.tsx
  client/src/shared/icons/CalendarIcon.tsx
  client/src/shared/icons/TaskIcon.tsx
  client/src/shared/twin/home-content.style.ts
  client/src/shared/twin/settings-modal.style.ts
  client/tailwind.config.js
Labels: for-review, dependent, Approved by Joshua ✅, AJ is Reviewing 🔎

#7 [slackana-03] - [BE] Implement User Sign Up and Sign In Functionality
  api/app/Http/Controllers/Auth/AuthController.php
  api/app/Http/Controllers/Auth/EmailVerificationNotificationController.php
  api/app/Http/Controllers/Auth/NewPasswordController.php
  api/app/Http/Controllers/Auth/PasswordResetLinkController.php
  api/app/Http/Controllers/Auth/SignUpController.php
  api/app/Http/Controllers/Auth/VerifyEmailController.php
  api/app/Http/Kernel.php
  api/app/Http/Middleware/EnsureEmailIsVerified.php
  api/app/Http/Requests/Auth/SignInRequest.php
  api/app/Http/Requests/Auth/SignUpRequest.php
  api/app/Http/Resources/AvatarResource.php
  api/app/Http/Resources/UserResource.php
  api/app/Models/User.php
  api/app/Providers/AuthServiceProvider.php
  api/app/Providers/RouteServiceProvider.php
  api/composer.json
  api/composer.lock
  api/config/app.php
  api/config/cors.php
  api/config/filesystems.php
  api/config/sanctum.php
  api/database/migrations/2022_09_26_123345_create_media_table.php
  api/package.json
  api/public/assets/avatar/avatar-1.png
  api/public/assets/avatar/avatar-10.png
  api/public/assets/avatar/avatar-11.png
  api/public/assets/avatar/avatar-12.png
  api/public/assets/avatar/avatar-2.png
  api/public/assets/avatar/avatar-3.png
  api/public/assets/avatar/avatar-4.png
  api/public/assets/avatar/avatar-5.png
  api/public/assets/avatar/avatar-6.png
  api/public/assets/avatar/avatar-7.png
  api/public/assets/avatar/avatar-8.png
  api/public/assets/avatar/avatar-9.png
  api/public/media/1/avatar-5.png
  api/resources/css/app.css
  api/resources/js/app.js
  api/resources/js/bootstrap.js
  api/resources/views/.gitkeep
  api/resources/views/welcome.blade.php
  api/routes/api.php
  api/routes/auth.php
  api/routes/web.php
  api/tests/Feature/Auth/AuthenticationTest.php
  api/tests/Feature/Auth/EmailVerificationTest.php
  api/tests/Feature/Auth/PasswordResetTest.php
  api/tests/Feature/Auth/RegistrationTest.php
  api/vite.config.js
Labels: for-review, dependent, don't merge, Approved by John ✅, Approved by Joshua ✅

#13 [slackana-48] - [BE] Fix Sign Up Controller
  api/routes/auth.php
Labels: for-review, Approved by Joshua ✅

#15 [slackana-50] - [BE] Fix User Image not found in Deployment Server
  api/.gitignore
  api/app/Http/Controllers/Auth/SignUpController.php
  api/public/media/1/avatar-5.png
Labels: Approved by John ✅, For Code Review 💻, Approved by Joshua ✅

#14 [slackana-49] - [Markup] Fix User Layout and Group Icons
  client/next.config.js
  client/src/components/organisms/Drawer/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/ProjectHeader/index.tsx
  client/src/components/organisms/Sidebar/index.tsx
  client/src/components/templates/HomeLayout/index.tsx
  client/src/pages/index.tsx
  client/src/shared/twin/header.styles.ts
  client/src/shared/twin/home-layout.styles.ts
  client/src/shared/twin/project-header.styles.ts
  client/src/shared/twin/sidebar.styles.ts
Labels: For Code Review 💻, Approved by AJ ✅

#21 [slackana-40] - [Markup] Create Project Overview Page
  client/public/images/team/backend.png
  client/public/images/team/designer.png
  client/public/images/team/frontend.png
  client/public/images/team/qa.png
  client/src/components/atoms/SubmitButton/index.tsx
  client/src/components/molecules/InputTags/index.tsx
  client/src/components/molecules/MembersTemplate/index.tsx
  client/src/components/molecules/TeamTemplate/index.tsx
  client/src/pages/team/[id]/overview.tsx
  client/src/shared/css/tailwind.css
  client/src/shared/jsons/membersData.ts
  client/src/shared/jsons/teamTempoData.ts
Labels: dependent, For Code Review 💻, Approved by Joshua ✅, Approved by AJ ✅

#20 [slackana-44] - [Markup] Create team modal
  client/src/components/molecules/InputTags/index.tsx
  client/src/components/molecules/TeamTemplate/index.tsx
  client/src/pages/team/[id]/overview.tsx
Labels: dependent, For Code Review 💻, Approved by Joshua ✅
