Repository abduljalilpalala/ps-slackana, pull requests merged in 2022-11, with the labels that each got.

#134 [604] - [BugTask] Nudge Function not working as intended in Dev Server
  client/src/hooks/pusherNudge.ts
Labels: For Code Review 💻

#118 [588] - [Markup] Create Chat Page
  client/src/components/atoms/TextEditorButtons/index.tsx
  client/src/components/molecules/AvatarList/index.tsx
  client/src/components/molecules/ChatEditor/index.tsx
  client/src/components/molecules/ChatList/index.tsx
  client/src/components/molecules/MessageOptionDropdown/index.tsx
  client/src/components/molecules/ProjectStatusDropdown/index.tsx
  client/src/components/molecules/ThreadList/index.tsx
  client/src/components/organisms/BoardSection/index.tsx
  client/src/components/organisms/ProjectHeader/index.tsx
  client/src/components/templates/Tooltip/index.tsx
  client/src/pages/team/[id]/chat.tsx
  client/src/pages/team/[id]/overview.tsx
  client/src/shared/icons/BlockquoteIcon.tsx
  client/src/shared/icons/DownRightIcon.tsx
  client/src/shared/icons/ListNumberIcon.tsx
  client/src/shared/icons/SendIcon.tsx
  client/src/shared/icons/StrikeThroughIcon.tsx
  client/src/shared/icons/ThreadMessageIcon.tsx
  client/src/shared/interfaces/index.ts
  client/src/shared/jsons/chatData.ts
  client/src/shared/twin/project-header.styles.ts
  client/src/shared/types/index.ts
  client/tailwind.config.js
Labels: For Code Review 💻

#136 [426] - [BE] Implement Fetch, Upload, Rename, Delete and Download File Functionality
  api/app/Http/Controllers/ProjectFileController.php
  api/app/Http/Resources/ProjectFileResource.php
  api/app/Models/Project.php
  api/composer.json
  api/composer.lock
  api/routes/api.php
Labels: For Code Review 💻, Approved by Joshua 👌, Approved by RJ :white_check_mark:

#137 [082] - [FE] Implement Real-time Task Assignee Notification
  api/app/Events/AssignTaskEvent.php
  api/app/Http/Controllers/NotificationController.php
  api/app/Http/Controllers/TaskAssignmentController.php
  api/app/Http/Controllers/TaskController.php
  api/app/Notifications/AssignTaskNotification.php
  api/database/migrations/2022_10_27_031834_create_notifications_table.php
  api/routes/api.php
  client/src/components/molecules/NotificationPopover/index.tsx
  client/src/hooks/notificationMethods.ts
  client/src/utils/formatMoment.ts
Labels: For Code Review 💻

#138 [437] - [BE] Implement, Fetch, Mark as Read, and Filter Notifications functionality according to a selected project
  api/app/Http/Controllers/NotificationController.php
  api/app/Http/Controllers/UserController.php
Labels: For Code Review 💻

#142 [430] - [Markup] Create Manage Files Page
  client/package.json
  client/src/components/atoms/Pagination/index.tsx
  client/src/components/molecules/FileList/EditFilenameDialog.tsx
  client/src/components/molecules/FileList/FIleItem.tsx
  client/src/components/molecules/FileList/TableHead.tsx
  client/src/components/molecules/FileList/index.tsx
  client/src/components/organisms/ProjectHeader/index.tsx
  client/src/hooks/pusherNudge.ts
  client/src/pages/team/[id]/files.tsx
  client/src/shared/css/globals.css
  client/src/shared/css/tailwind.css
  client/src/shared/icons/PDFIcon.tsx
  client/src/shared/icons/SortIcon.tsx
  client/src/shared/icons/WordIcon.tsx
  client/src/shared/interfaces/index.ts
  client/src/shared/jsons/fileIconType.ts
  client/src/shared/jsons/filesData.ts
  client/src/shared/types/index.ts
  client/yarn.lock
Labels: For Code Review 💻

#139 [493] - [FE] Do automatic input search on the add member search field.
  client/src/components/organisms/AddMemberModal/index.tsx
  client/src/hooks/debounceSearch.ts
Labels: For Code Review 💻, Approved by Joshua 👌

#140 [590] - [BE] Setup Message Model and Migrations
  api/app/Models/Project.php
  api/app/Models/ProjectMessage.php
  api/database/migrations/2022_10_28_105048_create_project_messages_table.php
Labels: For Code Review 💻, Approved by Joshua 👌

#144 [699] - [BugTask] Notification red dot must be gone after the user click the notification bell button and notification must be gone if the user open the task notification slider.
  api/app/Http/Controllers/NotificationSeenController.php
  api/database/migrations/2022_11_02_071347_add_seen_at_column.php
  api/routes/api.php
  client/src/components/molecules/NotificationPopover/index.tsx
  client/src/components/molecules/TaskList/index.tsx
  client/src/components/organisms/TaskSlider/index.tsx
  client/src/hooks/notificationMethods.ts
Labels: For Code Review 💻, Approved by Joshua 👌, Approved by Jermaine ⭐

#145 [705] - [BugTask] Can still assign the same member in the task even if the task is already assigned to that specific member. Also can receive notification.
  api/app/Http/Controllers/TaskAssignmentController.php
Labels: For Code Review 💻, Approved by Joshua 👌, Approved by Jermaine ⭐

#143 [436] - [Markup] Create Notifications Page
  client/src/components/molecules/FileList/FIleItem.tsx
  client/src/components/molecules/NotificationList/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/components/templates/NotificationLayout/index.tsx
  client/src/pages/notifications/projects/[id].tsx
  client/src/shared/interfaces/index.ts
  client/src/shared/jsons/notificationsData.ts
Labels: For Code Review 💻, Approved by RJ :white_check_mark:, Approved by Jermaine ⭐

#146 [427] - [FE] Integrate Fetch, and Upload Files Functionality
  api/app/Enums/PermissionEnum.php
  api/app/Http/Controllers/ProjectFileController.php
  api/app/Http/Requests/StoreProjectFileRequest.php
  api/composer.lock
  api/database/seeders/PermissionRolesSeeder.php
  api/database/seeders/PermissionSeeder.php
  client/src/components/molecules/FileList/FIleItem.tsx
  client/src/components/molecules/FileList/index.tsx
  client/src/components/molecules/FileListSkeleton/index.tsx
  client/src/components/molecules/PaginationSkeleton/index.tsx
  client/src/hooks/fileMethods.ts
  client/src/pages/team/[id]/files.tsx
  client/src/redux/files/fileService.ts
  client/src/redux/files/fileSlice.ts
  client/src/redux/files/fileType.ts
  client/src/redux/store.ts
  client/src/shared/icons/BlankSlateTableIcon.tsx
  client/src/shared/interfaces/index.ts
  client/src/shared/jsons/fileIconType.ts
  client/src/shared/jsons/filesData.ts
  client/src/utils/formatFiles.ts
Labels: For Code Review 💻

#141 [592] - [BE] Implement Fetch and Send, Edit, Delete Message Functionality
  api/app/Events/SendProjectMessageEvent.php
  api/app/Http/Controllers/ProjectMessageController.php
  api/app/Http/Requests/ProjectMessageRequest.php
  api/app/Http/Resources/ProjectMessageResource.php
  api/app/Models/ProjectMessage.php
  api/database/migrations/2022_11_03_053256_change_user_id_in_users_table.php
  api/database/seeders/ProjectSeeder.php
  api/routes/api.php
Labels: For Code Review 💻, Approved by Joshua 👌, Approved by RJ :white_check_mark:, Approved by Jermaine ⭐

#147 [438] - [FE] Integrate Fetch and Filter Notifications functionality according to a selected project
  api/app/Events/AssignTaskEvent.php
  api/app/Http/Controllers/TaskAssignmentController.php
  api/app/Http/Controllers/TaskController.php
  client/src/components/molecules/NotificationList/index.tsx
  client/src/components/molecules/NotificationPopover/index.tsx
  client/src/hooks/notificationMethods.ts
  client/src/pages/notifications/projects/[id].tsx
  client/src/shared/interfaces/index.ts
  client/src/shared/jsons/notificationsData.ts
Labels: For Code Review 💻, Approved by Joshua 👌, Approved by Jermaine ⭐

#148 [440] - [FE] Integrate Mark as Read Notifications Functionality and Implement Redirect Notification
  client/src/components/molecules/NotificationList/index.tsx
  client/src/shared/interfaces/index.ts
Labels: dependent ❗, For Code Review 💻, Approved by Joshua 👌, Approved by Jermaine ⭐

#149 [431] - [FE] Integrate Rename, Delete and Download File Functionality
  api/app/Http/Controllers/ProjectFileController.php
  client/package.json
  client/src/components/molecules/FileList/DeleteConfirmModal.tsx
  client/src/components/molecules/FileList/FIleItem.tsx
  client/src/components/molecules/FileList/index.tsx
  client/src/hooks/fileMethods.ts
  client/src/pages/team/[id]/files.tsx
  client/yarn.lock
Labels: For Code Review 💻, Approved by Joshua 👌, Approved by RJ :white_check_mark:

#150 [228] - [BugTask] Uploaded files or pictures can still be uploaded again
  api/app/Http/Controllers/ProjectFileController.php
  client/src/components/molecules/FileList/DeleteConfirmModal.tsx
  client/src/pages/team/[id]/files.tsx
Labels: For Code Review 💻, Approved by Joshua 👌, Approved by AJ ✅

#153 [141] - [BugTask] The task can be clicked anywhere you don't click on the name section
  api/app/Http/Controllers/NotificationController.php
  client/src/components/molecules/NotificationList/index.tsx
Labels: For Code Review 💻, Approved by Joshua 👌, Approved by AJ ✅

#152 [297] - [BugTask] File icons not displaying on some files
  client/src/components/molecules/FileList/FIleItem.tsx
  client/src/shared/icons/PDFIcon.tsx
  client/src/shared/icons/WordIcon.tsx
  client/src/shared/types/index.ts
  client/src/utils/mapMimeToFileIcon.ts
Labels: For Code Review 💻, Approved by AJ ✅

#156 [269] - [BugTask] When renaming the file with existing filename, ask the user to continue by adding a number suffix or cancel
  api/app/Http/Controllers/ProjectFileController.php
  api/app/Utils/ProjectFileUtils.php
  client/src/components/molecules/FileList/EditFilenameDialog.tsx
  client/src/components/molecules/FileList/EditFilenameModal.tsx
  client/src/components/molecules/FileList/index.tsx
Labels: For Code Review 💻

#157 [551] - [BugTask] When uploading a document file with an existing filename, there is no suffix number in the document files
  api/app/Http/Controllers/ProjectFileController.php
  api/app/Http/Resources/ProjectFileResource.php
  api/app/Utils/ProjectFileUtils.php
  client/src/components/molecules/FileList/EditFilenameDialog.tsx
  client/src/redux/files/fileType.ts
  client/src/utils/formatFiles.ts
Labels: For Code Review 💻, Approved by Joshua 👌, Approved by AJ ✅

#155 [292] - [BugTask] Fix Seeders in Back end
  api/app/Http/Controllers/Auth/SignUpController.php
  api/app/Http/Controllers/ProjectController.php
  api/app/Http/Controllers/ProjectFileController.php
  api/app/Models/Project.php
  api/app/Models/User.php
  api/database/seeders/PermissionRolesSeeder.php
  api/database/seeders/ProjectSeeder.php
  api/routes/web.php
Labels: For Code Review 💻, Approved by Joshua 👌

#160 [391] - [BugTask] the member of the project does not show the border style and Pen Icon
  client/src/pages/team/[id]/overview.tsx
Labels: For Code Review 💻

#154 [593] - [FE] Integrate Fetch and Send, Edit, Delete Message Functionality
  api/app/Http/Controllers/ProjectMessageController.php
  client/package.json
  client/src/components/molecules/ChatEditor/index.tsx
  client/src/components/molecules/ChatList/index.tsx
  client/src/components/molecules/MessageOptionDropdown/index.tsx
  client/src/pages/team/[id]/chat.tsx
  client/src/pages/team/[id]/files.tsx
  client/src/redux/chat/chatService.ts
  client/src/redux/chat/chatSlice.ts
  client/src/redux/chat/chatType.ts
  client/src/redux/store.ts
  client/src/shared/css/globals.css
  client/src/shared/interfaces/index.ts
  client/src/utils/mdeOptions.ts
  client/tailwind.config.js
  client/yarn.lock
Labels: For Code Review 💻

#161 [638] - [BugTask] In another account, the name displayed is incorrect when sending a message and no 3 Dots icon is displayed
  api/app/Http/Controllers/ProjectMessageController.php
  api/app/Http/Controllers/ProjectMessageThreadController.php
  api/app/Http/Requests/ProjectMessageRequest.php
  api/app/Models/Project.php
  api/database/seeders/ProjectSeeder.php
  client/src/pages/team/[id]/chat.tsx
  client/src/redux/chat/chatSlice.ts
Labels: Approved, Approved by Joshua 👌, Approved by RJ :white_check_mark:, Approved by Jermaine ⭐

#162 [071] - [FE] Highlight Message when Thread Option is selected
  client/src/components/molecules/ChatList/index.tsx
Labels: For Code Review 💻, Approved by RJ :white_check_mark:, Approved by Jermaine ⭐

#163 [648] - [BugTask] Default images is not displayed int the user's profile on the chat page
  client/src/components/molecules/ChatList/index.tsx
  client/src/components/molecules/ThreadList/index.tsx
  client/src/components/organisms/ProjectHeader/index.tsx
  client/src/pages/team/[id]/chat.tsx
Labels: For Code Review 💻, Approved by Joshua 👌, Approved by RJ :white_check_mark:, Approved by Jermaine ⭐

#164 [066] - [FE] Upload Multiple Files in Manage Files Section Functionality
  api/app/Http/Controllers/ProjectFileController.php
  api/app/Utils/ProjectFileUtils.php
  client/src/hooks/fileMethods.ts
  client/src/pages/team/[id]/files.tsx
  client/src/redux/files/fileService.ts
  client/src/redux/files/fileSlice.ts
Labels: For Code Review 💻, Approved by Joshua 👌

#165 [650] - [BugTask] User cannot send a message when pressing the Enter key
  client/src/components/molecules/ChatEditor/index.tsx
  client/src/pages/team/[id]/chat.tsx
  client/src/redux/chat/chatSlice.ts
Labels: For Code Review 💻, Approved by AJ ✅

#166 [079] - [FE] Get Repository Commit and Merge Events to Chat
  api/app/Enums/PullRequestStatusEnum.php
  api/app/Http/Controllers/ProjectController.php
  api/app/Jobs/HandleMergeWebhookJob.php
  api/app/Jobs/HandlePushWebhookJob.php
  api/app/Models/Project.php
  api/composer.json
  api/composer.lock
  api/database/migrations/2022_11_06_052254_make_project_member_nullable_message.php
  client/src/components/molecules/ChatList/index.tsx
  client/src/components/molecules/NotificationList/index.tsx
  client/src/components/molecules/NotificationPopover/index.tsx
  client/src/components/molecules/ProjectActionDropdown/index.tsx
  client/src/components/molecules/ThreadList/index.tsx
  client/src/components/organisms/ProjectHeader/index.tsx
  client/src/redux/chat/chatType.ts
  client/src/shared/interfaces/index.ts
Labels: For Code Review 💻, Approved by Joshua 👌, Approved by AJ ✅, Approved by Jermaine ⭐

#167 [616] - [FE] Design remove member account in Chat Message
  client/src/components/molecules/ChatList/index.tsx
Labels: For Code Review 💻, Approved by RJ :white_check_mark:, Approved by Jermaine ⭐

#170 [069] - [FE] Drag and Drop Files in Manage Files Section Functionality
  api/composer.lock
  client/package.json
  client/src/components/molecules/FileList/DragFileUploadDialog.tsx
  client/src/components/molecules/FileList/FIleItem.tsx
  client/src/pages/team/[id]/files.tsx
  client/src/shared/icons/FileUploadImage.tsx
  client/yarn.lock
Labels: For Code Review 💻, Approved by Joshua 👌, Approved by AJ ✅, Approved by RJ :white_check_mark:

#168 [760] - [BugTask] When clicking on the thread icon in mobile view, the thread component will slide from the right side of the screen
  client/src/components/molecules/ChatList/index.tsx
  client/src/components/molecules/MessageOptionDropdown/index.tsx
  client/src/components/molecules/ThreadList/index.tsx
  client/src/components/organisms/ProjectHeader/index.tsx
  client/src/components/organisms/ThreadDrawer/index.tsx
  client/src/pages/team/[id]/chat.tsx
Labels: For Code Review 💻, Approved by AJ ✅, Approved by RJ :white_check_mark:, Approved by Jermaine ⭐

#171 [080] - [BE] Implement Mute Notifications when Project is archived Functionality
  api/app/Http/Controllers/NudgeMemberController.php
  api/app/Http/Controllers/ProjectMessageController.php
  api/app/Http/Controllers/TaskAssignmentController.php
  api/app/Http/Controllers/TaskController.php
  api/app/Jobs/HandleMergeWebhookJob.php
  api/app/Jobs/HandlePushWebhookJob.php
  client/src/hooks/notificationMethods.ts
  client/src/hooks/pusherNudge.ts
Labels: For Code Review 💻, Approved by Jermaine ⭐

#173 [040] - [FE] Integrate Mute Nudge Functionality for a specific Project
  api/app/Http/Controllers/NudgeMemberController.php
  client/src/components/atoms/SwitchToggle/index.tsx
  client/src/components/molecules/NotificationList/index.tsx
  client/src/components/molecules/ProjectActionDropdown/index.tsx
  client/src/components/organisms/ProjectHeader/index.tsx
  client/src/components/organisms/ProjectSettingsModal/index.tsx
  client/src/redux/project/projectService.ts
  client/src/redux/project/projectSlice.ts
  client/src/redux/project/projectType.ts
  client/src/shared/icons/InfoIcon.tsx
  client/src/shared/twin/project-action-dropdown.styles.ts
Labels: For Code Review 💻

#172 [764] - [FE] If greater than 2MB or more than 20 files, inform the user that it is limited up to 20 files only and the size of each file must not be greater than 2MB
  api/routes/api.php
  client/src/hooks/fileMethods.ts
  client/src/redux/files/fileService.ts
  client/src/shared/types/index.ts
  client/src/utils/formatIniValues.ts
Labels: For Code Review 💻, Approved by Joshua 👌, AJ is Reviewing 🔎

#177 [443] - [BugTask] CORS issue: Redirect is not allowed for a preflight request fix
  client/src/redux/files/fileService.ts
Labels: For Code Review 💻, Approved by Joshua 👌

#178 [684] - [BugTask] Disable button on setting repo when input is empty
  client/src/components/organisms/ProjectSettingsModal/index.tsx
Labels: For Code Review 💻

#179 [849] - [BugTask] Add task skeleton while data is loading on task creation
  api/app/Http/Controllers/TaskController.php
  client/src/components/molecules/TaskList/index.tsx
  client/src/hooks/taskMethods.ts
  client/src/pages/team/[id]/board.tsx
  client/src/redux/section/sectionSlice.ts
Labels: For Code Review 💻, Approved by Joshua 👌

#181 [848] - [BugTask] Fix error toast for section and task create, update and delete
  client/src/hooks/taskMethods.ts
  client/src/pages/team/[id]/board.tsx
Labels: For Code Review 💻, Approved by Joshua 👌, Approved by Jermaine ⭐

#182 [670] - [BugTask] Display the name of uploaded/renamed/deleted files
  client/src/components/molecules/FileList/DragFileUploadDialog.tsx
  client/src/components/molecules/FileList/FIleItem.tsx
  client/src/components/molecules/FileList/index.tsx
  client/src/hooks/fileMethods.ts
  client/src/pages/team/[id]/files.tsx
  client/src/redux/files/fileService.ts
  client/src/redux/files/fileSlice.ts
Labels: For Code Review 💻

#184 [850] - [BugTask] Disable remove button in the task slider when task is removed
  client/src/components/organisms/TaskSlider/index.tsx
Labels: For Code Review 💻, Approved by Joshua 👌

#183 [881] - [BugTask] The user changes the password, invalid input, the error message is displayed and the setting modal is closed, the error message is still displayed
  client/src/components/organisms/SettingsModal/index.tsx
  client/src/components/organisms/TaskSlider/index.tsx
  client/src/redux/setting/settingService.ts
  client/src/shared/types/index.ts
  client/src/shared/validation/index.ts
Labels: For Code Review 💻, Approved by RJ :white_check_mark:

#185 [865] - [BugTask] Redirect to 404 when task is not found
  client/src/components/molecules/NotificationPopover/index.tsx
  client/src/pages/notifications/projects/[id].tsx
  client/src/utils/getServerSideProps.ts
Labels: For Code Review 💻, Approved and Merged ✔️, Approved by Joshua 👌, Approved by AJ ✅

#187 [254] - [Markup] - Modify Team On-hover style in Overview Page
  client/src/components/molecules/TeamTemplate/index.tsx
  client/src/components/organisms/SettingsModal/index.tsx
Labels: For Code Review 💻

#188 [252] - [Markup] - Modify Home Page Design
  client/src/components/atoms/SeeMore/index.tsx
  client/src/components/organisms/DropDownFilter/index.tsx
  client/src/components/templates/ProjectTemplate/index.tsx
  client/src/pages/index.tsx
  client/src/shared/twin/home-content.style.ts
Labels: For Code Review 💻

#189 [219] - [FE] Implement remove avatar on user settings
  api/app/Http/Controllers/UpdateUserSettingsController.php
  api/public/assets/avatar/default-avatar.png
  api/routes/api.php
  client/src/components/organisms/SettingsModal/index.tsx
  client/src/hooks/taskMethods.ts
  client/src/redux/setting/settingService.ts
  client/src/redux/setting/settingSlice.ts
  client/src/shared/twin/settings-modal.style.ts
Labels: For Code Review 💻, Approved by Joshua 👌

#191 [561] - [BugTask] Add loading state in notification popover
  api/app/Jobs/HandleMergeWebhookJob.php
  api/app/Jobs/HandlePushWebhookJob.php
  api/app/Models/ProjectMessage.php
  client/src/components/molecules/NotificationPopover/index.tsx
  client/src/hooks/notificationMethods.ts
Labels: For Code Review 💻, Approved by Joshua 👌

#174 [654] - [BugTask] Should scroll down after a new message is sent in the Thread Section
  client/src/components/molecules/ChatList/EditMessageDialog.tsx
  client/src/components/molecules/ThreadList/EditMessageThreadDialog.tsx
  client/src/components/molecules/ThreadList/index.tsx
  client/src/components/organisms/ThreadDrawer/index.tsx
  client/src/components/templates/DialogTemplate/index.tsx
  client/src/pages/team/[id]/chat.tsx
Labels: For Code Review 💻, Approved by AJ ✅

#192 [304] - [FE] Implement Search Command Pallete
  client/src/components/molecules/CommandPallete/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/components/templates/HomeLayout/index.tsx
  client/src/redux/project/projectSlice.ts
  client/src/shared/interfaces/index.ts
Labels: For Code Review 💻, Approved by AJ ✅

#194 [617] - [FE] Implement Mark As All Read Notifications Functionality
  api/app/Http/Controllers/MarkReadNotificationController.php
  api/routes/api.php
  client/src/components/molecules/NotificationPopover/index.tsx
  client/src/hooks/notificationMethods.ts
  client/src/pages/notifications/projects/[id].tsx
  client/src/redux/notification/notificationSlice.ts
  client/src/redux/store.ts
Labels: Work In Progress 🛠️, Approved by Joshua 👌, Approved by AJ ✅

#193 [614] - [FE] Implement Sort Files Functionality
  client/src/components/molecules/CommandPallete/index.tsx
  client/src/components/molecules/FileList/TableHead.tsx
  client/src/components/molecules/FileList/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/shared/types/index.ts
Labels: For Code Review 💻

#197 [537] - [FE] Implement Search Files Functionality
  client/src/components/molecules/FileList/index.tsx
  client/src/pages/team/[id]/files.tsx
Labels: For Code Review 💻

#199 [672] - [BugTask] On the notification page the user can click and see the search modal
  client/src/components/organisms/Header/index.tsx
  client/src/components/templates/NotificationLayout/index.tsx
Labels: For Code Review 💻

#198 [311] - [FE] Implement Message Not Successfully Sent Functionality
  client/src/components/molecules/ChatEditor/ChatThreadEditor.tsx
  client/src/components/molecules/ChatEditor/index.tsx
  client/src/components/molecules/ChatList/index.tsx
  client/src/components/molecules/ThreadList/index.tsx
  client/src/components/organisms/ThreadDrawer/index.tsx
  client/src/pages/notifications/projects/[id].tsx
  client/src/shared/types/index.ts
Labels: For Code Review 💻

#202 [211] - [BugTask] The first message in Chat should be at the bottom displayed
  client/src/pages/team/[id]/chat.tsx
Labels: For Code Review 💻, Approved by AJ ✅
