Repository abduljalilpalala/ps-slackana, pull requests merged in 2022-10, with the labels that each got.

#22 [slackana]-53 - [Bugtask] Fix Project Status Dropdown overlay
  client/src/components/organisms/DropDownFilter/index.tsx
  client/src/pages/index.tsx
Labels: For Code Review 💻, Approved by Joshua ✅

#23 [slackana]-52 [Bugtask] Fix Settings Modal Title
  client/src/components/organisms/SettingsModal/index.tsx
  client/src/components/templates/DialogBox/index.tsx
Labels: For Code Review 💻, Approved by Joshua ✅

#25 [slackana]-54 [Bugtask] Fix Filter Dropdown is not Responsive
  client/src/components/molecules/UserMenuDropdown/index.tsx
Labels: For Code Review 💻

#26 [slackana-04] - [FE] Integrate User Sign Up Functionality
  api/app/Http/Controllers/Auth/SignUpController.php
  client/next.config.js
  client/package.json
  client/src/components/molecules/AuthForm/index.tsx
  client/src/hooks/authStatus.ts
  client/src/hooks/reduxSelector.ts
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/src/pages/sign-in.tsx
  client/src/pages/sign-up.tsx
  client/src/redux/auth/authService.ts
  client/src/redux/auth/authSlice.ts
  client/src/redux/store.ts
  client/src/shared/lib/axios.ts
  client/src/shared/types/index.ts
  client/src/shared/validation/index.ts
  client/src/utils/getServerSideProps.ts
  client/src/utils/handleAxiosError.ts
  client/yarn.lock
Labels: For Code Review 💻, Approved by Joshua ✅

#30 [slackana-55] - [Bugtask] Remove excess Padding in Add Member Modal Header
  client/src/components/organisms/AddMemberModal/index.tsx
Labels: For Code Review 💻, Approved by Joshua ✅

#31 [slackana-06] - [FE] Integrate User Sign In Functionality
  api/routes/auth.php
  client/src/components/molecules/AuthForm/index.tsx
  client/src/components/molecules/UserMenuDropdown/index.tsx
  client/src/components/organisms/Sidebar/index.tsx
  client/src/components/templates/AuthLayout/index.tsx
  client/src/hooks/authMethods.ts
  client/src/hooks/authStatus.ts
  client/src/pages/index.tsx
  client/src/pages/sign-in.tsx
  client/src/pages/sign-up.tsx
  client/src/redux/auth/authService.ts
  client/src/redux/auth/authSlice.ts
  client/src/shared/lib/axios.ts
  client/src/shared/types/index.ts
Labels: For Code Review 💻, Approved by Joshua ✅

#32 [slackana-07] -[FE] Implement Route Protection
  client/src/pages/team/[id]/board.tsx
  client/src/pages/team/[id]/chat.tsx
  client/src/pages/team/[id]/overview.tsx
Labels: dependent, Approved by Joshua ✅

#33 [slackana-57] - [Markup] Sidebar Persisted State
  client/src/components/organisms/Sidebar/index.tsx
  client/src/components/templates/HomeLayout/index.tsx
Labels: Approved by John ✅, For Code Review 💻, Approved by AJ ✅

#34 [slackana-09] - [BE] Create Project API
  api/app/Enums/ProjectStatusEnum.php
  api/app/Http/Controllers/ProjectController.php
  api/app/Http/Resources/MemberResource.php
  api/app/Http/Resources/ProjectResource.php
  api/app/Http/Resources/ProjectRoleResource.php
  api/app/Http/Resources/ProjectStatusResource.php
  api/app/Http/Resources/TeamResource.php
  api/app/Http/Resources/UserResource.php
  api/app/Models/Project.php
  api/app/Models/ProjectMember.php
  api/app/Models/ProjectStatus.php
  api/app/Models/Team.php
  api/app/Models/User.php
  api/database/migrations/2022_10_03_162045_create_project_statuses_table.php
  api/database/migrations/2022_10_03_162046_create_projects_table.php
  api/database/migrations/2022_10_03_162403_create_teams_table.php
  api/database/migrations/2022_10_03_162517_create_project_members_table.php
  api/database/migrations/2022_10_03_164225_create_member_teams_table.php
  api/database/seeders/DatabaseSeeder.php
  api/database/seeders/ProjectSeeder.php
  api/database/seeders/ProjectStatusSeeder.php
  api/public/assets/project-icons/project-icon-1.png
  api/public/assets/project-icons/project-icon-10.png
  api/public/assets/project-icons/project-icon-11.png
  api/public/assets/project-icons/project-icon-12.png
  api/public/assets/project-icons/project-icon-13.png
  api/public/assets/project-icons/project-icon-14.png
  api/public/assets/project-icons/project-icon-15.png
  api/public/assets/project-icons/project-icon-16.png
  api/public/assets/project-icons/project-icon-17.png
  api/public/assets/project-icons/project-icon-18.png
  api/public/assets/project-icons/project-icon-19.png
  api/public/assets/project-icons/project-icon-2.png
  api/public/assets/project-icons/project-icon-20.png
  api/public/assets/project-icons/project-icon-3.png
  api/public/assets/project-icons/project-icon-4.png
  api/public/assets/project-icons/project-icon-5.png
  api/public/assets/project-icons/project-icon-6.png
  api/public/assets/project-icons/project-icon-7.png
  api/public/assets/project-icons/project-icon-8.png
  api/public/assets/project-icons/project-icon-9.png
  api/routes/api.php
Labels: Approved by John ✅, For Code Review 💻, Approved by Joshua ✅

#36 [slackana-12] - [BE] Implement Update User Information, Avatar, and Password Functionality
  api/app/Enums/NotificationEnum.php
  api/app/Enums/UserStatusEnum.php
  api/app/Http/Controllers/Auth/AuthController.php
  api/app/Http/Controllers/Auth/SignUpController.php
  api/app/Http/Controllers/ChangeUserPasswordController.php
  api/app/Http/Controllers/UpdateUserSettingsController.php
  api/app/Http/Controllers/UserController.php
  api/app/Http/Requests/ChangeUserPasswordRequest.php
  api/app/Http/Requests/UpdateUserAvatarRequest.php
  api/app/Http/Requests/UpdateUserRequest.php
  api/app/Http/Resources/NotificationResource.php
  api/app/Http/Resources/UserResource.php
  api/app/Models/NotificationSetting.php
  api/app/Models/Setting.php
  api/app/Models/User.php
  api/app/Rules/MatchOldPassword.php
  api/database/migrations/2022_10_04_112246_create_settings_table.php
  api/database/migrations/2022_10_04_112306_create_notification_settings_table.php
  api/database/seeders/DatabaseSeeder.php
  api/database/seeders/SettingSeeder.php
  api/routes/api.php
  api/routes/web.php
Labels: Work-In-Progress, Approved by John ✅, Approved by Joshua ✅

#37 [slackana-19] - [BE] Implement Create Project Functionality
  api/app/Http/Controllers/Auth/SignUpController.php
  api/app/Http/Controllers/ProjectController.php
  api/app/Http/Resources/ProjectResource.php
  api/routes/web.php
Labels: Work-In-Progress, Approved by John ✅, Approved by Joshua ✅

#38 [slackana-36] - [BE] Implement Set Project Status Functionality
  api/app/Http/Controllers/ProjectStatusController.php
  api/app/Http/Requests/ProjectStatusRequest.php
  api/database/seeders/NotificationSettingSeeder.php
  api/routes/api.php
  api/routes/web.php
Labels: Work-In-Progress, Approved by John ✅, Approved by Joshua ✅

#39 [slackana-16] - [BE] Implement Filter Projects Functionality
  api/app/Enums/ProjectStatusEnum.php
  api/app/Http/Controllers/ProjectController.php
Labels: Work-In-Progress, Approved by John ✅, Approved by Joshua ✅

#41 [slackana-42] - [BE] Implement Edit Project Functionality
  api/app/Http/Controllers/ProjectController.php
  api/app/Http/Requests/UpdateProjectRequest.php
Labels: Work-In-Progress, Approved by John ✅, Approved by Joshua ✅

#42 [slackana-45] - [BE] Implement Team CRUD Functionality
  api/app/Http/Controllers/ProjectTeamController.php
  api/app/Http/Requests/StoreProjectRequest.php
  api/routes/api.php
Labels: Work-In-Progress, Approved by John ✅, Approved by Joshua ✅

#44 [slackana-25] - [BE] Implement Add and Remove Member Functionality
  api/app/Http/Controllers/ProjectMemberController.php
  api/app/Http/Controllers/ProjectTeamController.php
  api/app/Http/Controllers/UserController.php
  api/app/Http/Requests/StoreProjectMemberRequest.php
  api/app/Http/Requests/UpdateProjectMemberRequest.php
  api/app/Models/Team.php
  api/routes/api.php
Labels: Work-In-Progress, Approved by John ✅, Approved by Joshua ✅

#45 [slackana-27] - [BE] Implement Leave Project Functionality
  api/app/Http/Controllers/ProjectMemberStatusController.php
  api/routes/api.php
Labels: Work-In-Progress, dependent, Approved by John ✅, Approved by Joshua ✅

#46 [slackana-31] - [BE] Implement Assign Team Lead Functionality
  api/app/Http/Controllers/ProjectMemberStatusController.php
  api/routes/api.php
Labels: Work-In-Progress, dependent, Approved by John ✅, Approved by Joshua ✅

#47 [slackana-33] - [BE] Implement Set MVP Functionality
  api/app/Http/Controllers/ProjectController.php
  api/app/Http/Controllers/ProjectMemberStatusController.php
  api/app/Http/Controllers/ProjectTeamController.php
  api/app/Http/Controllers/UpdateUserSettingsController.php
  api/app/Http/Resources/TeamResource.php
  api/app/Models/Team.php
  api/public/assets/team-icons/team-1.png
  api/public/assets/team-icons/team-2.png
  api/public/assets/team-icons/team-3.png
  api/public/assets/team-icons/team-4.png
  api/public/assets/team-icons/team-5.png
  api/public/assets/team-icons/team-6.png
  api/public/assets/team-icons/team-7.png
  api/public/assets/team-icons/team-8.png
  api/public/assets/team-icons/team-9.png
  api/routes/api.php
Labels: Work-In-Progress, dependent, Approved by John ✅, Approved by Joshua ✅

#55 [slackana-13] - [FE] Integrate Update User Information, Avatar, and Password Functionality
  client/next.config.js
  client/package.json
  client/public/images/avatar.png
  client/public/images/image-dummy.png
  client/public/images/team/intern.png
  client/public/images/team/null.png
  client/public/images/team/projectmanager.png
  client/public/images/team/softwareqa.png
  client/public/images/team/teamlead.png
  client/yarn.lock
Labels: For Code Review 💻, Approved by Joshua ✅

#56 [slackana-15] - [FE] Fetch Project Data from API
  client/src/components/atoms/SeeMore/index.tsx
  client/src/components/atoms/Skeletons/BoxSkeleton/index.tsx
  client/src/components/atoms/Skeletons/ImageSkeleton/index.tsx
  client/src/components/atoms/Skeletons/LineSkeleton/index.tsx
  client/src/components/atoms/Skeletons/LoadingScreen/index.tsx
  client/src/components/atoms/Skeletons/LoadingScreen/loading.module.css
  client/src/shared/jsons/dummyTeamIcon.ts
  client/src/utils/getDate.ts
  client/src/utils/getGreetings.ts
  client/src/utils/isLoggedIn.ts
  client/src/utils/skeletonAnimation.ts
  client/src/utils/statusChecker.ts
Labels: For Code Review 💻, Approved by Joshua ✅

#54 [slackana-17] - [FE] Integrate Filter Projects Functionality
  client/src/components/atoms/SubmitButton/index.tsx
  client/src/redux/project/projectService.ts
  client/src/redux/project/projectSlice.ts
  client/src/redux/project/projectType.ts
  client/src/redux/setting/settingService.ts
  client/src/redux/setting/settingSlice.ts
Labels: For Code Review 💻, Approved by Joshua ✅

#57 [slackana-20] - [FE] Integrate Create Project Functionality
  client/src/components/molecules/InputTags/index.tsx
  client/src/components/molecules/MembersTemplate/index.tsx
  client/src/components/molecules/ProjectActionDropdown/index.tsx
  client/src/components/molecules/ProjectStatusDropdown/index.tsx
  client/src/components/molecules/TeamTemplate/index.tsx
  client/src/components/molecules/UserMenuDropdown/index.tsx
  client/src/components/molecules/UserMenuPopover/index.tsx
Labels: For Code Review 💻, Approved by Joshua ✅

#58 [slackana-24] - [FE] Fetch Project Members Data from API
  client/src/components/organisms/AddMemberModal/index.tsx
  client/src/components/organisms/Drawer/index.tsx
  client/src/components/organisms/DropDownFilter/index.tsx
  client/src/components/organisms/ProjectHeader/index.tsx
  client/src/components/organisms/SettingsModal/index.tsx
  client/src/components/organisms/Sidebar/index.tsx
  client/src/components/templates/ProjectLayout/index.tsx
  client/src/components/templates/ProjectTemplate/index.tsx
Labels: For Code Review 💻, Approved by Joshua ✅

#53 [slackana-37] - [FE] Integrate Set Status Functionality
  client/src/pages/index.tsx
  client/src/pages/team/[id]/overview.tsx
Labels: For Code Review 💻, Approved by Joshua ✅

#49 [slackana-39] - [FE] Integrate Archive and Unarchive Functionality to Overview Page
  client/src/redux/auth/authService.ts
  client/src/redux/auth/authSlice.ts
  client/src/redux/store.ts
Labels: For Code Review 💻, Approved by Joshua ✅

#50 [slackana-41] - [FE] Fetch Project Details from API
  README.md
Labels: For Code Review 💻, Approved by Joshua ✅

#51 [slackana-43] - [FE] Integrate Edit Functionality to Overview Page
  client/src/shared/jsons/projectStatusData.ts
Labels: For Code Review 💻, Approved by Joshua ✅

#65 [480] - [BE] Set-up Section Model and Migrations
  api/app/Models/Project.php
  api/app/Models/Section.php
  api/database/migrations/2022_10_07_065228_create_sections_table.php
  api/database/seeders/ProjectSeeder.php
  client/src/components/molecules/TeamTemplate/index.tsx
  client/src/components/templates/ProjectListTemplate/index.tsx
Labels: For Code Review 💻, Approved by Joshua ✅

#67 [476] - [BE] Implement Fetch, Add, Update and Delete Section Functionality
  api/app/Http/Controllers/SectionController.php
  api/app/Http/Requests/StoreSectionRequest.php
  api/app/Http/Requests/UpdateSectionRequest.php
  api/app/Http/Resources/SectionResource.php
  api/app/Http/Traits/CheckProjectRole.php
  api/routes/api.php
Labels: For Code Review 💻

#66 [479] - [Markup] Create Project Board Section Component
  client/package.json
  client/public/svgs/logo.svg
  client/src/components/organisms/BoardSection/index.tsx
  client/src/components/templates/BoardWrapper/index.tsx
  client/src/pages/_document.tsx
  client/src/pages/team/[id]/board.tsx
  client/src/shared/interfaces/index.ts
  client/src/shared/jsons/boardData.ts
  client/tailwind.config.js
  client/yarn.lock
Labels: for-review

#73 [477] - [FE] Integrate Fetch, Add, Update and Delete Section Functionality
  client/src/components/organisms/BoardSection/index.tsx
  client/src/pages/team/[id]/board.tsx
  client/src/redux/section/sectionService.ts
  client/src/redux/section/sectionSlice.ts
  client/src/redux/store.ts
  client/src/shared/types/index.ts
Labels: Approved by John ✅, For Code Review 💻, Approved by Joshua ✅, Approved by AJ ✅

#70 [482] - [BE] Implement Fetch Tasks, Create Task, Rename title and Remove Task Functionality
  api/app/Http/Controllers/SectionController.php
  api/app/Http/Controllers/TaskController.php
  api/app/Http/Requests/StoreTaskRequest.php
  api/app/Http/Requests/UpdateTaskRequest.php
  api/app/Http/Resources/SectionResource.php
  api/app/Http/Resources/TaskResource.php
  api/app/Models/Task.php
  api/database/migrations/2022_10_12_033922_modify_tasks_table.php
  api/database/seeders/ProjectSeeder.php
  api/routes/api.php
Labels: Approved by John ✅, For Code Review 💻, Approved by Joshua ✅, Approved by AJ ✅

#71 [575] - [BE] Implement Edit Description, Estimated Time, Actual Time Finished Functionality
  api/app/Http/Controllers/TaskDetailsController.php
  api/app/Http/Requests/UpdateTaskDetailsRequest.php
  api/database/factories/SectionFactory.php
  api/database/factories/TaskFactory.php
  api/database/seeders/ProjectSeeder.php
  api/routes/api.php
Labels: Approved by John ✅, For Code Review 💻, Approved by Joshua ✅, Approved by AJ ✅

#75 [105] - [BugTask] Unable to add project if there is no inputs in the description unrequired field
  client/src/pages/index.tsx
  client/src/pages/team/[id]/overview.tsx
Labels: For Code Review 💻

#76 [578]-[BE] Implement Set Task Status Functionality
  api/app/Http/Controllers/CompleteTaskController.php
  api/routes/api.php
Labels: Approved by John ✅, For Code Review 💻, Approved by Joshua ✅, Approved by AJ ✅

#77 [582]-[BE] Implement Assign Due Dates Functionality
  api/app/Http/Controllers/TaskDueDateController.php
  api/app/Http/Requests/UpdateTaskDueDateRequest.php
  api/database/migrations/2022_10_12_145732_drop_due_date_on_tasks_table.php
  api/database/migrations/2022_10_12_145750_change_due_date_on_tasks_table.php
  api/routes/api.php
Labels: Approved by John ✅, For Code Review 💻, Approved by Joshua ✅

#78 [584]-[BE] Implement Assign Tasks Functionality
  api/app/Http/Controllers/TaskAssignmentController.php
  api/app/Http/Requests/UpdateTaskAssignmentRequest.php
  api/database/factories/SectionFactory.php
  api/routes/api.php
Labels: Approved by John ✅, For Code Review 💻, Approved by Joshua ✅, Approved by AJ ✅

#72 [481] - [Markup] Create Project Board Task Component
  client/package.json
  client/src/components/molecules/AddSection/index.tsx
  client/src/components/molecules/AddTask/index.tsx
  client/src/components/molecules/TaskList/index.tsx
  client/src/components/organisms/BoardSection/index.tsx
  client/src/components/templates/BoardWrapper/index.tsx
  client/src/components/templates/Tooltip/index.tsx
  client/src/pages/_app.tsx
  client/src/pages/team/[id]/board.tsx
  client/src/shared/css/globals.css
  client/src/shared/jsons/assigneeData.ts
  client/src/shared/jsons/boardData.ts
  client/src/shared/jsons/dummySectionWithTasks.ts
  client/src/shared/jsons/dummyTasks.tsx
  client/src/shared/lib/next-progress.tsx
  client/src/shared/twin/home-layout.styles.ts
  client/tailwind.config.js
  client/yarn.lock
Labels: Approved by John ✅, For Code Review 💻, Approved by RJ :white_check_mark:

#74 [slackana-26] - [FE] Integrate Add, Edit, Filter, Search and Remove Member Functionality
  api/app/Http/Controllers/ProjectController.php
  api/app/Http/Controllers/ProjectMemberController.php
  api/app/Http/Controllers/UserController.php
  api/app/Http/Requests/UpdateProjectRequest.php
  api/app/Http/Resources/ProjectResource.php
  api/app/Http/Resources/TeamResource.php
  api/app/Http/Resources/UserResource.php
  api/app/Models/Project.php
  api/app/Utils/Permission.php
  client/src/components/atoms/AddPeopleButton/index.tsx
  client/src/components/molecules/MemberList/MemberListType.ts
  client/src/components/molecules/MemberList/index.tsx
  client/src/components/molecules/MembersTemplate/index.tsx
  client/src/components/molecules/PeopeList/index.tsx
  client/src/components/molecules/ProjectActionDropdown/index.tsx
  client/src/components/molecules/ProjectStatusDropdown/index.tsx
  client/src/components/molecules/TeamTemplate/index.tsx
  client/src/components/molecules/UserMenuDropdown/index.tsx
  client/src/components/molecules/UserMenuPopover/index.tsx
  client/src/components/organisms/AddMemberModal/AddMemberFilterType.ts
  client/src/components/organisms/AddMemberModal/index.tsx
  client/src/components/organisms/Drawer/index.tsx
  client/src/components/organisms/MemberFilter/MemberFilterType.ts
  client/src/components/organisms/MemberFilter/index.tsx
  client/src/components/organisms/MemberOption/MemberOptionType.ts
  client/src/components/organisms/MemberOption/index.tsx
  client/src/components/organisms/PeopleOption/index.tsx
  client/src/components/organisms/ProjectHeader/index.tsx
  client/src/components/organisms/SettingsModal/SettingsType.ts
  client/src/components/organisms/SettingsModal/index.tsx
  client/src/components/organisms/Sidebar/index.tsx
  client/src/components/templates/ProjectListTemplate/index.tsx
  client/src/components/templates/ProjectTemplate/index.tsx
  client/src/pages/404.tsx
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/src/pages/team/[id]/overview.tsx
  client/src/redux/auth/authSlice.ts
  client/src/redux/member/memberService.ts
  client/src/redux/member/memberSlice.ts
  client/src/redux/member/memberType.ts
  client/src/redux/project/projectService.ts
  client/src/redux/project/projectSlice.ts
  client/src/redux/store.ts
  client/src/shared/icons/CrownIcon.tsx
  client/src/shared/icons/FistIcon.tsx
  client/src/shared/icons/StarIcon.tsx
  client/src/shared/types/index.ts
  client/src/utils/UnderContruction.tsx
  client/src/utils/darkToaster.ts
Labels: For Code Review 💻, Approved by Joshua ✅, Approved by AJ ✅, Approved by RJ :white_check_mark:

#80 [716] - [BugTask] Apply Faker and Fix Board Permissions
  api/composer.json
  client/src/pages/team/[id]/board.tsx
Labels: Approved by Joshua ✅

#82 [28] - [FE] Integrate Leave Project Functionality
  client/src/components/molecules/MemberList/index.tsx
  client/src/components/organisms/MemberOption/index.tsx
  client/src/components/organisms/SettingsModal/index.tsx
  client/src/components/templates/ProjectTemplate/index.tsx
Labels: For Code Review 💻

#81 [32] - [FE] Integrate Assign Team Lead Functionality
  client/src/redux/member/memberService.ts
  client/src/redux/member/memberSlice.ts
Labels: For Code Review 💻

#83 [34] - [FE] Integrate MVP Functionality
  README.md
  client/src/pages/index.tsx
  client/src/shared/icons/FistIcon.tsx
Labels: For Code Review 💻

#79 [113] - [Markup] Create Task Modal Slider
  client/src/components/molecules/AddSection/index.tsx
  client/src/components/molecules/TaskList/index.tsx
  client/src/components/organisms/BoardSection/index.tsx
  client/src/components/organisms/TaskSlider/index.tsx
  client/src/components/templates/BoardWrapper/index.tsx
  client/src/components/templates/Tooltip/index.tsx
  client/src/pages/_app.tsx
  client/src/pages/team/[id]/board.tsx
Labels: For Code Review 💻

#85 [574] - [FE] Integrate CRUD Task Functionality, Integrate Assign Due Date, Integrate Assign Task
  api/app/Http/Controllers/ProjectController.php
  api/app/Http/Controllers/ProjectMemberController.php
  api/app/Http/Controllers/SectionController.php
  api/app/Http/Controllers/TaskReorderController.php
  api/app/Http/Requests/StoreTaskRequest.php
  api/app/Http/Resources/TaskResource.php
  api/routes/api.php
  client/src/components/molecules/AddTask/index.tsx
  client/src/components/molecules/TaskList/index.tsx
  client/src/components/organisms/BoardSection/index.tsx
  client/src/hooks/memberMethods.ts
  client/src/hooks/projectMethods.ts
  client/src/hooks/taskMethods.ts
  client/src/pages/team/[id]/board.tsx
  client/src/redux/member/memberService.ts
  client/src/redux/member/memberSlice.ts
  client/src/redux/store.ts
  client/src/redux/task/taskService.ts
  client/src/redux/task/taskSlice.ts
  client/src/shared/types/index.ts
Labels: Work-In-Progress, Approved by Joshua ✅

#86 [579] - [FE] Integrate Set Task Status Functionality
  client/src/components/molecules/TaskList/index.tsx
  client/src/components/templates/BoardWrapper/index.tsx
  client/src/components/templates/ProjectLayout/index.tsx
  client/src/hooks/taskMethods.ts
  client/src/pages/team/[id]/board.tsx
  client/src/redux/task/taskService.ts
  client/src/redux/task/taskSlice.ts
Labels: For Code Review 💻, Approved by Joshua ✅, Approved by AJ ✅

#87 [581] - [FE] Integrate Set Own Task Status Functionality
  api/app/Http/Controllers/CompleteTaskController.php
  api/app/Http/Controllers/ProjectController.php
  api/app/Http/Controllers/ProjectMemberController.php
  client/src/components/molecules/TaskList/index.tsx
  client/src/hooks/projectMethods.ts
  client/src/pages/team/[id]/board.tsx
Labels: For Code Review 💻

#88 [844] - [BugTask] Replace useEffect from Overview page to ProjectLayoutPage
  client/src/components/molecules/MemberList/index.tsx
  client/src/components/molecules/PeopeList/index.tsx
  client/src/components/organisms/AddMemberModal/index.tsx
  client/src/components/organisms/ProjectHeader/index.tsx
  client/src/pages/index.tsx
  client/src/pages/team/[id]/overview.tsx
  client/src/redux/project/projectSlice.ts
Labels: For Code Review 💻, Approved by Joshua ✅, Approved by AJ ✅, Approved by RJ :white_check_mark:

#89 [11-01] - [Markup] Remove Notifications for Google Meeting reminder
  README.md
  client/src/components/molecules/PeopeList/index.tsx
  client/src/components/organisms/SettingsModal/index.tsx
  client/src/shared/twin/settings-modal.style.ts
Labels: For Code Review 💻, Approved by Joshua ✅, Approved by AJ ✅

#90 [855] - [Markup] Set project description in overview page to be un-resizable
  client/src/pages/team/[id]/overview.tsx
Labels: For Code Review 💻, Approved by Joshua ✅, Approved by AJ ✅

#92 [26-01] - [Markup] Add member border status in Overview Page
  client/src/components/molecules/MembersTemplate/index.tsx
Labels: For Code Review 💻, Approved by Joshua ✅

#91 [072] - [BugTask] Fix Board Section Full height Scrollable-X Content
  client/src/components/molecules/TaskList/index.tsx
  client/src/components/organisms/BoardSection/index.tsx
  client/src/components/templates/ProjectLayout/index.tsx
Labels: For Code Review 💻

#93 [481-1] - [Markup] Add Rename Task Title
  client/src/components/molecules/TaskList/index.tsx
Labels: For Code Review 💻

#96 [023] - [BugTask] Full name is cut upon hovering in the upper right user DP.
  client/src/components/molecules/UserMenuDropdown/index.tsx
  client/src/shared/twin/user-menu-dropdown.styles.ts
Labels: dependent, don't merge, For Code Review 💻

#97 [753] - [BugTask] The archive dropdown does not extend beyond the sidebar
  client/src/shared/twin/project-action-dropdown.styles.ts
Labels: For Code Review 💻, Approved by AJ ✅

#94 [076] - [BugTask] Section Title dispatches update even no changes were made
  client/src/components/organisms/BoardSection/index.tsx
Labels: Approved by AJ ✅

#98 [197] - [BugTask] The scroll does not exceed the title
  client/src/components/molecules/TaskList/index.tsx
  client/src/components/organisms/BoardSection/index.tsx
Labels: For Code Review 💻

#99 [841] - [BugTask] Fix Default Image not displaying when link is broken
  client/src/components/molecules/AddTask/index.tsx
  client/src/components/molecules/MemberList/index.tsx
  client/src/components/molecules/MembersTemplate/index.tsx
  client/src/components/molecules/PeopeList/index.tsx
  client/src/components/molecules/TaskList/index.tsx
  client/src/components/molecules/TeamTemplate/index.tsx
  client/src/components/molecules/UserMenuDropdown/index.tsx
  client/src/components/molecules/UserMenuPopover/index.tsx
  client/src/components/organisms/Drawer/index.tsx
  client/src/components/organisms/ProjectHeader/index.tsx
  client/src/components/organisms/SettingsModal/index.tsx
  client/src/components/organisms/Sidebar/index.tsx
  client/src/components/organisms/TaskSlider/index.tsx
  client/src/components/templates/ProjectListTemplate/index.tsx
  client/src/components/templates/ProjectTemplate/index.tsx
  client/src/helpers/handleImageError.ts
Labels: For Code Review 💻, Approved by Joshua ✅

#95 [576] - [FE] Integrate Edit Task Slider Details
  api/app/Http/Controllers/TaskDetailsController.php
  api/routes/api.php
  client/src/components/molecules/TaskList/index.tsx
  client/src/components/organisms/TaskSlider/index.tsx
  client/src/hooks/projectMethods.ts
  client/src/hooks/taskMethods.ts
  client/src/pages/team/[id]/board.tsx
  client/src/redux/task/taskService.ts
  client/src/redux/task/taskSlice.ts
  client/src/shared/types/index.ts
Labels: For Code Review 💻, Approved by Joshua ✅, Approved by AJ ✅

#102 [226] - [Markup] Create Nudge Component
  client/src/components/molecules/MemberList/index.tsx
  client/src/components/molecules/MembersTemplate/index.tsx
  client/src/utils/nudgeMember.tsx
Labels: For Code Review 💻, Approved by Joshua ✅, Approved by AJ ✅

#101 [758] - [BugTask] In mobile the set status project is very close to add member icon
  client/src/components/molecules/ProjectStatusDropdown/index.tsx
  client/src/components/organisms/Drawer/index.tsx
  client/src/pages/_document.tsx
  client/src/shared/twin/notification-popover.styles.ts
  client/tailwind.config.js
Labels: Approved by John ✅, For Code Review 💻, Approved by AJ ✅

#104 [729] - [BugTask] Fix the default images in the board details
  client/src/components/organisms/TaskSlider/index.tsx
Labels: For Code Review 💻, Approved by Joshua ✅

#110 [755] - [BugTask] - Options Button in task component is hidden while renaming
  client/src/components/molecules/TaskList/index.tsx
  client/src/components/organisms/TaskSlider/index.tsx
  client/src/hooks/taskMethods.ts
Labels: For Code Review 💻, Approved by Joshua ✅, Approved by AJ ✅

#109 [765] - [BugTask] The eye icon, text and the task dropdown will be aligned
  client/src/components/molecules/TaskList/index.tsx
Labels: For Code Review 💻

#113 [024] - [BugTask] Ellipses is not displayed in the Assignee field if the name is too long.
  client/src/components/organisms/TaskSlider/index.tsx
Labels: For Code Review 💻

#114 [833] - [FE] Add color representation for due dates
  client/src/components/molecules/TaskList/index.tsx
  client/src/components/organisms/TaskSlider/index.tsx
  client/src/hooks/taskMethods.ts
  client/src/pages/team/[id]/board.tsx
Labels: For Code Review 💻, Approved by Joshua ✅

#112 [29] - [BE] Implement Nudge Functionality
  api/app/Events/NudgeMemberEvent.php
  api/app/Http/Controllers/NudgeMemberController.php
  api/composer.json
  api/composer.lock
  api/config/app.php
  api/routes/api.php
Labels: For Code Review 💻

#117 [30] - [FE] Integrate Nudge Functionality
  api/app/Events/NudgeMemberEvent.php
  client/package.json
  client/public/sounds/notification-nudge.mp3
  client/src/components/molecules/MemberList/MemberListType.ts
  client/src/components/molecules/MemberList/index.tsx
  client/src/components/organisms/AddMemberModal/index.tsx
  client/src/components/organisms/ProjectHeader/index.tsx
  client/src/hooks/nudge.ts
  client/src/hooks/pusherNudge.ts
  client/src/pages/team/[id]/overview.tsx
  client/src/shared/lib/pusher.ts
  client/src/utils/nudgeMember.tsx
  client/tailwind.config.js
  client/yarn.lock
Labels: Approved by Joshua ✅

#116 [036] - [Markup] Customize React Datepicker Style
  client/src/components/molecules/TaskList/index.tsx
  client/src/components/organisms/TaskSlider/index.tsx
  client/src/shared/css/globals.css
Labels: For Code Review 💻

#119 [618] - [FE] Add Environment variables at next.config.js for Pusher JS
  client/.env.example
  client/next.config.js
Labels: For Code Review 💻

#121 [622] - [BugTask] Edit Task Details not wrking as expected at Dev Server
  client/src/components/organisms/TaskSlider/index.tsx
  client/src/hooks/taskMethods.ts
Labels: For Code Review 💻

#122 [249] - [BugTask] Fix Project Sidebar Active Link
  client/src/components/organisms/Sidebar/index.tsx
Labels: Approved by John ✅, For Code Review 💻

#126 [965] - [Bugtask] the border should also be red for the outdated due date
  api/app/Http/Controllers/TaskReorderController.php
  api/database/seeders/ProjectSeeder.php
  client/src/components/organisms/TaskSlider/index.tsx
Labels: For Code Review 💻, Approved by Joshua ✅, Approved by AJ ✅

#127 [680] - [FE] Add Protected Routes when a user is not a member of the Project
  api/app/Http/Controllers/ProjectMemberController.php
  client/src/components/molecules/MemberList/index.tsx
  client/src/utils/getServerSideProps.ts
Labels: For Code Review 💻, Approved by Joshua ✅

#128 [680-1] - [BugTask] Fix Protected Routes in Dev Server
  client/src/utils/getServerSideProps.ts
Labels: For Code Review 💻, Approved by Joshua ✅

#129 [087] - [FE] Implement Draggable and Persisting Tasks and Functionality
  api/app/Http/Controllers/TaskPositionController.php
  api/app/Http/Controllers/TaskReorderController.php
  api/app/Http/Controllers/TaskSectionController.php
  api/app/Http/Requests/UpdateTaskSectionRequest.php
  api/routes/api.php
  client/package.json
  client/src/components/molecules/AddTask/index.tsx
  client/src/components/molecules/TaskList/index.tsx
  client/src/components/organisms/BoardSection/index.tsx
  client/src/components/organisms/TaskSlider/index.tsx
  client/src/hooks/taskMethods.ts
  client/src/pages/team/[id]/board.tsx
  client/src/redux/section/sectionSlice.ts
  client/src/redux/task/taskService.ts
  client/src/redux/task/taskSlice.ts
  client/yarn.lock
Labels: For Code Review 💻, Approved by Joshua ✅

#131 [495] - [FE] Indicate project name in the nudge notification
  README.md
  api/.env.example
  api/app/Events/NudgeMemberEvent.php
  api/app/Http/Controllers/ProjectMemberController.php
  client/src/components/organisms/ProjectHeader/index.tsx
  client/src/components/templates/ProjectListTemplate/index.tsx
  client/src/hooks/pusherNudge.ts
  client/src/utils/nudgeMember.tsx
Labels: For Code Review 💻, Approved by Joshua ✅

#132 [088] - [FE] Allow Own Task to be moved Function
  client/src/pages/team/[id]/board.tsx
Labels: For Code Review 💻, Approved by Joshua ✅

#130 [491] - [FE] Additional icons for editable fields in the Project details.
  client/src/pages/team/[id]/overview.tsx
Labels: For Code Review 💻

#133 [881] - [BugTask] Cannot horizontally scroll when dragging tasks
  client/src/components/molecules/TaskList/index.tsx
  client/src/components/organisms/BoardSection/index.tsx
  client/src/pages/team/[id]/board.tsx
Labels: For Code Review 💻, Approved by Joshua ✅
